% This script compiles the inference code of the random regression forest. 
clearvars; close all; clc;
fprintf('Compling the random forest inference code ...\n');
fprintf('gcc and libEigen is required!\n');

if ismac
  fprintf('Compiling on MAC. You need to install g++\n');
  mex -v forestRegrInferenceMac.cpp ...
       -I/usr/local/include ...
       CFLAGS="\$CFLAGS" ...
       CXXFLAGS="\$CXXFLAGS" ...
       LDFLAGS="\$LDFLAGS" ...
       CC=g++ CXX=g++ LD=g++ ... 
       CXXOPTIMFLAGS="-O3 -DNDEBUG" COPTIMFLAGS="-O3 -DNDEBUG" LDOPTIMFLAGS="-O3" ...
       -output forestRegrInference
else
  mex -v forestRegrInference.cpp ...
    CFLAGS="\$CFLAGS -fopenmp" ...
    CXXFLAGS="\$CXXFLAGS -fopenmp" ...
    LDFLAGS="\$LDFLAGS -fopenmp " ...
    CXXOPTIMFLAGS="-O3 -DNDEBUG" COPTIMFLAGS="-O3 -DNDEBUG" LDOPTIMFLAGS="-O3"
end
